CREATE TABLE player_reward (
    id VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    reward INT,
    flag INT DEFAULT 1,
    PRIMARY KEY (id)
);
